plugins {
    id 'com.android.application'
}

android {
    namespace 'com.medsuite.pharmacy'
    compileSdk 34

    defaultConfig {
        applicationId 'com.medsuite.pharmacy'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '2.0.1'
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("KEYSTORE_PATH")
            if (ksPath != null) {
                storeFile file(ksPath)
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (System.getenv("KEYSTORE_PATH") != null) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Trusted Web Activity support (same library PWABuilder emits).
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
